#pragma once
#include <Arduino.h>

enum Event_Type {   EVENT_NONE,
                    EVENT_ENTER,EVENT_RIGHT,EVENT_LEFT,EVENT_UP,EVENT_DOWN,
                    EVENT_A1,EVENT_A2,EVENT_A3,EVENT_A4,EVENT_A5,
                    EVENT_B1,EVENT_B2,EVENT_B3,EVENT_B4,EVENT_B5,EVENT_B6,
                    EVENT_A1_DOUBLE,EVENT_A2_DOUBLE,EVENT_A3_DOUBLE,EVENT_A4_DOUBLE,EVENT_A5_DOUBLE,
                    EVENT_B1_DOUBLE,EVENT_B2_DOUBLE,EVENT_B3_DOUBLE,EVENT_B4_DOUBLE,EVENT_B5_DOUBLE,EVENT_B6_DOUBLE,
                    EVENT_A1_LONG,EVENT_A2_LONG,EVENT_A3_LONG,EVENT_A4_LONG,EVENT_A5_LONG,
                    EVENT_B1_LONG,EVENT_B2_LONG,EVENT_B3_LONG,EVENT_B4_LONG,EVENT_B5_LONG,EVENT_B6_LONG
                };


